name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Upgrade npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: List directory contents
        run: ls -R

      - name: Build
        run: npm run build --verbose

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: build
          token: ${{ secrets.GH_PAT }}
